/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get JWT token */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search and List Hotels
         * @description Search for hotels with filtering options. Returns a paginated list of lightweight hotel objects.
         */
        get: operations["searchHotels"];
        put?: never;
        /** Add a new Hotel (Admin/Manager only) */
        post: operations["addHotel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hotel Details with Room Types
         * @description Returns full hotel details along with embedded room types and their availability.
         */
        get: operations["getHotelById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/{id}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available rooms for a hotel */
        get: operations["getHotelRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1 - Calculate Price & Initiate Payment
         * @description Calculates total price based on formatting, checks availability/inventory reduction,
         *     and returns a Stripe Payment Intent client secret.
         */
        post: operations["createBookingIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2 - Finalize Booking
         * @description Called after successful payment on the client side to persist the booking in the DB.
         */
        post: operations["confirmBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/my-bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's booking history */
        get: operations["getUserBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/early-access-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Early Access User
         * @description Registers a new user for early access.
         */
        post: operations["createEarlyAccessUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example false */
            status?: boolean;
            /** @example 400 */
            statusCode?: number;
            /** @example Error message details */
            message?: string;
        };
        /** @enum {string} */
        UserRole: "CUSTOMER" | "HOTEL_MANAGER" | "ADMIN";
        /** @enum {string} */
        PaymentMode: "ONLINE" | "PAY_AT_HOTEL";
        /** @enum {string} */
        BookingStatus: "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
        User: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            passwordHash: string;
            role: components["schemas"]["UserRole"];
            phone?: string;
        };
        Amenity: {
            id: string;
            name: string;
            scopeId?: string | null;
        };
        Hotel: {
            id: string;
            name: string;
            city: string;
            address: string;
            description?: string | null;
            rating: number;
            lowestPrice?: number | null;
            images: string[];
            amenities: components["schemas"]["Amenity"][];
        };
        RoomType: {
            id: string;
            hotelId: string;
            name: string;
            price: number;
            capacity: number;
            totalInventory: number;
            images: string[];
            amenities: components["schemas"]["Amenity"][];
        };
        Booking: {
            id: string;
            userId: string;
            hotelId: string;
            roomTypeId: string;
            /** Format: date */
            checkIn: string;
            /** Format: date */
            checkOut: string;
            guestDetails: {
                name: string;
                /** Format: email */
                email: string;
                phone: string;
            };
            totalPrice: number;
            paymentMode: components["schemas"]["PaymentMode"];
            status: components["schemas"]["BookingStatus"];
            transactionId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email: string;
                    password: string;
                    role: components["schemas"]["UserRole"];
                    phone?: string;
                };
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: {
                            token?: string;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchHotels: {
        parameters: {
            query?: {
                /** @description Generic search term (name, city, etc.) */
                query?: string;
                /** @description Filter by location */
                city?: string;
                /** @description Check-in date (YYYY-MM-DD) */
                checkIn?: string;
                /** @description Check-out date (YYYY-MM-DD) */
                checkOut?: string;
                /** @description Number of guests */
                guests?: number;
                sortBy?: "price_low" | "price_high" | "rating";
                minPrice?: number;
                maxPrice?: number;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of hotels found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: {
                            data?: {
                                id?: string;
                                name?: string;
                                city?: string;
                                lowestPrice?: number;
                                images?: string[];
                                rating?: number;
                            }[];
                            meta?: {
                                total?: number;
                                page?: number;
                                limit?: number;
                            };
                        };
                    };
                };
            };
            /** @description Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addHotel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Hotel"];
            };
        };
        responses: {
            /** @description Hotel created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["Hotel"];
                    };
                };
            };
        };
    };
    getHotelById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hotel details with rooms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["Hotel"] & {
                            rooms?: (components["schemas"]["RoomType"] & {
                                /** @description Calculated availability for the dates */
                                available?: number;
                            })[];
                        };
                    };
                };
            };
            /** @description Hotel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHotelRooms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of rooms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["RoomType"][];
                    };
                };
            };
        };
    };
    createBookingIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    hotelId: string;
                    roomTypeId: string;
                    /** Format: date */
                    checkIn: string;
                    /** Format: date */
                    checkOut: string;
                    guests: number;
                };
            };
        };
        responses: {
            /** @description Payment Intent Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: {
                            paymentIntentId?: string;
                            clientSecret?: string;
                            totalPrice?: number;
                            /** @example INR */
                            currency?: string;
                        };
                    };
                };
            };
            /** @description Validation error or room not available */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    paymentIntentId: string;
                    guestDetails?: {
                        name?: string;
                        email?: string;
                        phone?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Booking Confirmed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["Booking"];
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUserBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["Booking"][];
                    };
                };
            };
        };
    };
    createEarlyAccessUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    name: string;
                    primaryUseCase: string;
                    company?: string;
                    role?: string;
                };
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict - Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
