/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get JWT token */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Available Hotels
         * @description Search for hotels by city/name with availability, filtering, and sorting.
         */
        get: operations["searchAvailableHotels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/my-hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hotels Managed by Current User */
        get: operations["getMyHotels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or Update a Hotel (Upsert) */
        post: operations["createHotel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/room-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or Update a Room Type (Upsert) */
        post: operations["createRoomType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/room-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a Room Type */
        delete: operations["deleteRoomType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a Hotel */
        delete: operations["deleteHotel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/manager/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Bookings for a Hotel (Manager Only) */
        get: operations["getManagerBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1 - Calculate Price & Initiate Payment
         * @description Calculates total price based on formatting, checks availability/inventory reduction,
         *     and returns a Stripe Payment Intent client secret.
         */
        post: operations["createBookingIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2 - Finalize Booking
         * @description Called after successful payment on the client side to persist the booking in the DB.
         */
        post: operations["confirmBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/my-bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's booking history */
        get: operations["getUserBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example false */
            status?: boolean;
            /** @example 400 */
            statusCode?: number;
            /** @example Error message details */
            message?: string;
        };
        /** @enum {string} */
        UserRole: "CUSTOMER" | "HOTEL_MANAGER" | "ADMIN";
        /** @enum {string} */
        PaymentMode: "ONLINE" | "PAY_AT_HOTEL";
        /** @enum {string} */
        BookingStatus: "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
        User: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            phone?: string;
        };
        Amenity: {
            id: string;
            name: string;
            scopeId?: string | null;
        };
        Hotel: {
            id: string;
            name: string;
            city: string;
            address: string;
            description?: string | null;
            rating: number;
            lowestPrice?: number | null;
            images: string[];
            amenities: string[];
            rooms?: components["schemas"]["RoomType"][];
        };
        RoomType: {
            id: string;
            hotelId: string;
            name: string;
            price: number;
            capacity: number;
            totalInventory: number;
            images: string[];
            amenities: string[];
        };
        Booking: {
            id: string;
            userId: string;
            hotelId: string;
            roomTypeId: string;
            /** Format: date */
            checkIn: string;
            /** Format: date */
            checkOut: string;
            guestDetails: {
                name: string;
                /** Format: email */
                email: string;
                phone: string;
            };
            totalPrice: number;
            paymentMode: components["schemas"]["PaymentMode"];
            status: components["schemas"]["BookingStatus"];
            transactionId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email: string;
                    password: string;
                    role: components["schemas"]["UserRole"];
                    phone?: string;
                };
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: {
                            token?: string;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchAvailableHotels: {
        parameters: {
            query: {
                /** @description Search term for City, Hotel Name, or Address (e.g., "Mumbai") */
                query: string;
                /** @description Check-in date (YYYY-MM-DD) */
                checkIn: string;
                /** @description Check-out date (YYYY-MM-DD) */
                checkOut: string;
                /** @description Number of guests (to filter room capacity) */
                guests?: number;
                /** @description Sort order for results */
                sortBy?: "price_low" | "price_high" | "rating";
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of results per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        status?: boolean;
                        /** @example 200 */
                        statusCode?: number;
                        data?: {
                            /**
                             * Format: uuid
                             * @description Hotel ID
                             */
                            id?: string;
                            /** @description Name of the hotel */
                            name?: string;
                            city?: string;
                            address?: string;
                            description?: string;
                            /**
                             * Format: float
                             * @example 4.5
                             */
                            avg_rating?: number;
                            /**
                             * Format: float
                             * @description Lowest price found among room types
                             */
                            starting_price?: number;
                            /**
                             * @description Comma-separated list of hotel amenities (from GROUP_CONCAT)
                             * @example wifi,pool,parking
                             */
                            hotel_amenities?: string;
                            /** @description List of active managers (from JSON_ARRAYAGG) */
                            manager_names?: string[];
                            /** @description Nested list of rooms with their specific availability */
                            rooms_details?: {
                                room_name?: string;
                                price?: number;
                                /** @description Calculated availability (Total - Booked) */
                                available_rooms?: number;
                                amenities?: string[];
                            }[];
                        }[];
                    };
                };
            };
            /** @description Bad Request (Invalid dates or missing parameters) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        status?: boolean;
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        status?: boolean;
                        message?: string;
                    };
                };
            };
        };
    };
    getMyHotels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of hotels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["Hotel"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createHotel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Hotel"];
            };
        };
        responses: {
            /** @description Hotel Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        message?: string;
                        data?: components["schemas"]["Hotel"];
                    };
                };
            };
        };
    };
    createRoomType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomType"];
            };
        };
        responses: {
            /** @description Room Type Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        message?: string;
                        data?: components["schemas"]["RoomType"];
                    };
                };
            };
        };
    };
    deleteRoomType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room Type Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                    };
                };
            };
            /** @description Forbidden (Not a manager) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteHotel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hotel Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                    };
                };
            };
            /** @description Forbidden (Not a manager) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getManagerBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bookings with rich details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: {
                            id?: string;
                            hotelName?: string;
                            status?: string;
                            /** Format: date-time */
                            checkIn?: string;
                            /** Format: date-time */
                            checkOut?: string;
                            totalPrice?: number;
                            guestName?: string;
                            guestEmail?: string;
                            guestPhone?: string;
                            guests?: {
                                name?: string;
                                phone?: string;
                                email?: string;
                            }[];
                            /** @description Summary string of rooms */
                            rooms?: string;
                        }[];
                    };
                };
            };
            /** @description Forbidden (Not a manager) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createBookingIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    hotelId: string;
                    roomTypeId: string;
                    /** Format: date */
                    checkIn: string;
                    /** Format: date */
                    checkOut: string;
                    guests: number;
                    paymentMode: components["schemas"]["PaymentMode"];
                    guestDetails?: {
                        name?: string;
                        email?: string;
                        phone?: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description Payment Intent Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: {
                            paymentIntentId?: string;
                            clientSecret?: string;
                            totalPrice?: number;
                            /** @example INR */
                            currency?: string;
                        };
                    };
                };
            };
            /** @description Validation error or room not available */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    bookingId: string;
                    paymentIntentId: string;
                    guestDetails?: {
                        name?: string;
                        email?: string;
                        phone?: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description Booking Confirmed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["Booking"];
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUserBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: boolean;
                        statusCode?: number;
                        message?: string;
                        data?: components["schemas"]["Booking"][];
                    };
                };
            };
        };
    };
}
